# Generated by Django 5.1.6 on 2025-03-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'MoMo'), ('vnpay', 'VNPay')], max_length=20),
        ),
    ]
