# Generated by Django 5.1.6 on 2025-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_paymentcategory_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGEMENT', 'Management'), ('RESIDENT', 'Resident')], default='RESIDENT', max_length=10),
        ),
    ]
