# Generated by Django 5.1.6 on 2025-04-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.CharField(choices=[('A', 'Tòa A'), ('B', 'Tòa B'), ('C', 'Tòa C'), ('D', 'Tòa D')], max_length=1),
        ),
    ]
