# Generated by Django 5.1.6 on 2025-04-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_alter_apartment_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.CharField(choices=[('A', 'Tòa A'), ('B', 'Tòa B'), ('C', 'Tòa C'), ('D', 'Tòa D'), ('E', 'Tòa E'), ('F', 'Tòa F')], max_length=1),
        ),
    ]
