# Generated by Django 5.1.6 on 2025-05-03 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0007_alter_apartment_building"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="floor",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ]
            ),
        ),
    ]
