# Generated by Django 5.2.2 on 2025-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_alter_apartment_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcategory',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
