# Generated by Django 5.2.2 on 2025-06-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_paymentcategory_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcategory',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
